---
- name: "Display 'show version' info"
  hosts: juniper
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars_files:
    - group_vars/juniper.yaml
  vars:
    ansible_python_interpreter: ~/.pyenv/versions/ansible-3.9.0/bin/python
    credentials:
      host: "{{ansible_host}}"
      username: "jcluser"
      password: "Juniper!1"

  tasks:
    - name: "Execute 'show version' on Junos OS"
      juniper_junos_command:
       provider: "{{credentials}}"
       commands:
       - show version
      register: response

    - name: "Print result"
      debug:
        var: response