- name: 'Get interface information'
  hosts: juniper
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars_files:
    - group_vars/juniper.yaml
  vars:
    ansible_python_interpreter: ~/.pyenv/versions/ansible-3.9.0/bin/python
    credentials:
      host: "{{ansible_host}}"
      username: "jcluser"
      password: "Juniper!1"

  tasks:
    - name: "RPC 'get-interface-information'"
      juniper_junos_rpc:
        provider: "{{credentials}}"
        rpcs:
          - "get-interface-information"
        kwargs:
          - terse: true
            interface_name: 'lo0'
      register: response

    - name: "Print the parsed response"
      debug:
        var: response['parsed_output']['interface-information']
