- name: 'Retrieve RSI information'
  hosts: juniper
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars_files:
    - group_vars/juniper.yaml
  vars:
    ansible_python_interpreter: ~/.pyenv/versions/ansible-3.9.0/bin/python
    credentials:
      host: "{{ansible_host}}"
      username: "jcluser"
      password: "Juniper!1"

  tasks:
    - name: "RPC 'get-support-information'"
      juniper_junos_rpc:
        provider: "{{credentials}}"
        rpc: "get-support-information"
        format: 'text'
        dest: "/var/tmp/{{ inventory_hostname }}.rsi"
        return_output: false
      register: response

    - name: "Print the response"
      debug:
        var: response