---
# hosts.yaml file
vMX1:
    hostname: 66.129.235.13
    port: 38005
    groups:
        - juniper

vMX2:
    hostname: 66.129.235.13
    port: 38008
    groups:
        - juniper

vMX3:
    hostname: 66.129.235.13
    port: 38011
    groups:
        - juniper

vMX4:
    hostname: 66.129.235.13
    port: 38014
    groups:
        - juniper

vMX5:
    hostname: 66.129.235.13
    port: 38017
    groups:
        - juniper

vMX6:
    hostname: 66.129.235.13
    port: 38020
    groups:
        - juniper